eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 9001
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:7400
  sleuth:
    sampler:
      percentage: 1.0

#spring.zipkin.base-url=http://localhost:9411
