eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8400
spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#spring.sleuth.sampler.percentage: 1.0